<?php

add_action('acf/init', 'masterclass_add_fields');
function masterclass_add_fields() {
    $repeater_id = 'field_64f5a696ab0b8';

    $g_fields = array(
        'players' => 'Участники',
        'hours'   => 'Часы',
        'age'     => 'Возраст'
    );
    $base_fields = array(
        array(
            'key' => 'base_fields',
            'label' => 'Основные поля',
            'name' => '',
            'aria-label' => '',
            'type' => 'tab',
            'instructions' => '',
            'required' => 0,
            'conditional_logic' => 0,
            'wrapper' => array(
                'width' => '',
                'class' => '',
                'id' => '',
            ),
            'acfe_save_meta' => 0,
            'placement' => 'top',
            'endpoint' => 0,
        ),

    );

    foreach ($g_fields as $tag => $label) {
        $base_fields[] = array(
            'key' => $tag . '_icon',
            'label' => $label . ' иконка',
            'name' => $tag . '_icon',
            'aria-label' => '',
            'type' => 'image',
            'instructions' => '',
            'required' => 0,
            'conditional_logic' => 0,
            'wrapper' => array(
                'width' => '40',
                'class' => '',
                'id' => '',
            ),
            'acfe_save_meta' => 0,
            'uploader' => '',
            'return_format' => 'id',
            'acfe_thumbnail' => 0,
            'min_width' => '',
            'min_height' => '',
            'min_size' => '',
            'max_width' => '',
            'max_height' => '',
            'max_size' => '',
            'mime_types' => '',
            'preview_size' => 'medium',
            'library' => 'all'
        );
        $base_fields[] = array(
            'key' => $tag,
            'label' => $label,
            'name' => $tag,
            'aria-label' => '',
            'type' => str_contains($tag, 'price') ? 'number' : 'text',
            'instructions' => '',
            'required' => 1,
            'conditional_logic' => 0,
            'wrapper' => array(
                'width' => '60',
                'class' => '',
                'id' => '',
            ),
            'acfe_save_meta' => 0,
            'default_value' => '',
            'min' => '',
            'max' => '',
            'placeholder' => '',
            'step' => '',
            'prepend' => '',
            'append' => ''
        );
    }

    $price_names = array(
        'players' => 'Участники',
        'master'  => 'Мастера',
        'hours'   => 'Часы',
        'age'     => 'Возраст',
        'price'   => 'Цена',
        'second_price' => 'Доп.участник'
    );

    $price_fields = array(
        array(
            'key' => 'title',
            'label' => 'Название',
            'name' => 'title',
            'aria-label' => '',
            'type' => 'text',
            'instructions' => '',
            'required' => 1,
            'conditional_logic' => 0,
            'wrapper' => array(
                'width' => '',
                'class' => '',
                'id' => '',
            ),
            'acfe_save_meta' => 0,
            'parent_repeater' => $repeater_id,
        ),
        array(
            'key' => 'background_img',
            'label' => 'Фоновая картинка',
            'name' => 'background',
            'aria-label' => '',
            'type' => 'image',
            'instructions' => '',
            'required' => 1,
            'conditional_logic' => 0,
            'wrapper' => array(
                'width' => '',
                'class' => '',
                'id' => '',
            ),
            'acfe_save_meta' => 0,
            'uploader' => '',
            'return_format' => 'id',
            'acfe_thumbnail' => 0,
            'min_width' => '',
            'min_height' => '',
            'min_size' => '',
            'max_width' => '',
            'max_height' => '',
            'max_size' => '',
            'mime_types' => '',
            'preview_size' => 'medium',
            'library' => 'all',
            'parent_repeater' => $repeater_id,
        ),
    );

    foreach ($price_names as $tag => $label) {
        $price_fields[] = array(
            'key' => $tag . '_icon',
            'label' => $label . ' иконка',
            'name' => $tag . '_icon',
            'aria-label' => '',
            'type' => 'image',
            'instructions' => '',
            'required' => 0,
            'conditional_logic' => 0,
            'wrapper' => array(
                'width' => '40',
                'class' => '',
                'id' => '',
            ),
            'acfe_save_meta' => 0,
            'uploader' => '',
            'return_format' => 'id',
            'acfe_thumbnail' => 0,
            'min_width' => '',
            'min_height' => '',
            'min_size' => '',
            'max_width' => '',
            'max_height' => '',
            'max_size' => '',
            'mime_types' => '',
            'preview_size' => 'medium',
            'library' => 'all',
            'parent_repeater' => $repeater_id,
        );
        $price_fields[] = array(
            'key' => $tag,
            'label' => $label,
            'name' => $tag,
            'aria-label' => '',
            'type' => str_contains($tag, 'price') ? 'number' : 'text',
            'instructions' => '',
            'required' => 1,
            'conditional_logic' => 0,
            'wrapper' => array(
                'width' => '60',
                'class' => '',
                'id' => '',
            ),
            'acfe_save_meta' => 0,
            'default_value' => '',
            'min' => '',
            'max' => '',
            'placeholder' => '',
            'step' => '',
            'prepend' => '',
            'append' => '',
            'parent_repeater' => $repeater_id,
        );
    }

    $fields = array_merge(
        $base_fields,
    array(
        array(
            'key' => 'field_64f5a65dab0b6',
            'label' => 'Цены',
            'name' => '',
            'aria-label' => '',
            'type' => 'tab',
            'instructions' => '',
            'required' => 0,
            'conditional_logic' => 0,
            'wrapper' => array(
                'width' => '',
                'class' => '',
                'id' => '',
            ),
            'acfe_save_meta' => 0,
            'placement' => 'top',
            'endpoint' => 0,
        ),
        array(
            'key' => 'field_64f5a696ab0b8',
            'label' => 'Цены',
            'name' => 'prices',
            'aria-label' => '',
            'type' => 'repeater',
            'instructions' => '',
            'required' => 0,
            'conditional_logic' => 0,
            'wrapper' => array(
                'width' => '',
                'class' => '',
                'id' => '',
            ),
            'acfe_save_meta' => 0,
            'acfe_repeater_stylised_button' => 0,
            'layout' => 'block',
            'pagination' => 0,
            'hide_collapse' => 0,
            'collapse_all_repeater' => 0,
            'btn-icon-only' => 0,
            'min' => 0,
            'max' => 0,
            'collapsed' => '',
            'button_label' => 'Добавить',
            'rows_per_page' => 20,
            'sub_fields' => $price_fields,
        ),
        array(
            'key' => 'field_64f5a67bab0b7',
            'label' => 'Дополнительно',
            'name' => '',
            'aria-label' => '',
            'type' => 'tab',
            'instructions' => '',
            'required' => 0,
            'conditional_logic' => 0,
            'wrapper' => array(
                'width' => '',
                'class' => '',
                'id' => '',
            ),
            'acfe_save_meta' => 0,
            'placement' => 'top',
            'endpoint' => 0,
        ),
        array(
            'key' => 'field_64f5a885ab0bd',
            'label' => 'Мы предоставляем',
            'name' => 'instruments',
            'aria-label' => '',
            'type' => 'repeater',
            'instructions' => '',
            'required' => 0,
            'conditional_logic' => 0,
            'wrapper' => array(
                'width' => '',
                'class' => '',
                'id' => '',
            ),
            'acfe_save_meta' => 0,
            'acfe_repeater_stylised_button' => 0,
            'layout' => 'table',
            'pagination' => 0,
            'hide_collapse' => 0,
            'collapse_all_repeater' => 0,
            'btn-icon-only' => 0,
            'min' => 0,
            'max' => 0,
            'collapsed' => '',
            'button_label' => 'Добавить',
            'rows_per_page' => 20,
            'sub_fields' => array(
                array(
                    'key' => 'field_64f5a8a3ab0be',
                    'label' => 'Название',
                    'name' => 'name',
                    'aria-label' => '',
                    'type' => 'text',
                    'instructions' => '',
                    'required' => 1,
                    'conditional_logic' => 0,
                    'wrapper' => array(
                        'width' => '',
                        'class' => '',
                        'id' => '',
                    ),
                    'acfe_save_meta' => 0,
                    'default_value' => '',
                    'maxlength' => '',
                    'placeholder' => '',
                    'prepend' => '',
                    'append' => '',
                    'parent_repeater' => 'field_64f5a885ab0bd',
                ),
            ),
        ),
        array(
            'key' => 'field_64f5a8b9ab0bf',
            'label' => 'Мы требуем',
            'name' => 'requires',
            'aria-label' => '',
            'type' => 'repeater',
            'instructions' => '',
            'required' => 0,
            'conditional_logic' => 0,
            'wrapper' => array(
                'width' => '',
                'class' => '',
                'id' => '',
            ),
            'acfe_save_meta' => 0,
            'acfe_repeater_stylised_button' => 0,
            'layout' => 'table',
            'pagination' => 0,
            'hide_collapse' => 0,
            'collapse_all_repeater' => 0,
            'btn-icon-only' => 0,
            'min' => 0,
            'max' => 0,
            'collapsed' => '',
            'button_label' => 'Добавить',
            'rows_per_page' => 20,
            'sub_fields' => array(
                array(
                    'key' => 'field_64f5a8d2ab0c0',
                    'label' => 'Название',
                    'name' => 'name',
                    'aria-label' => '',
                    'type' => 'text',
                    'instructions' => '',
                    'required' => 1,
                    'conditional_logic' => 0,
                    'wrapper' => array(
                        'width' => '',
                        'class' => '',
                        'id' => '',
                    ),
                    'acfe_save_meta' => 0,
                    'default_value' => '',
                    'maxlength' => '',
                    'placeholder' => '',
                    'prepend' => '',
                    'append' => '',
                    'parent_repeater' => 'field_64f5a8b9ab0bf',
                ),
            ),
        ),
        array(
            'key' => 'field_64f5a91dab0c1',
            'label' => 'Дополнительно',
            'name' => 'additional1',
            'aria-label' => '',
            'type' => 'repeater',
            'instructions' => '',
            'required' => 0,
            'conditional_logic' => 0,
            'wrapper' => array(
                'width' => '',
                'class' => '',
                'id' => '',
            ),
            'acfe_save_meta' => 0,
            'acfe_repeater_stylised_button' => 0,
            'layout' => 'table',
            'pagination' => 0,
            'hide_collapse' => 0,
            'collapse_all_repeater' => 0,
            'btn-icon-only' => 0,
            'min' => 0,
            'max' => 0,
            'collapsed' => '',
            'button_label' => 'Добавить',
            'rows_per_page' => 20,
            'sub_fields' => array(
                array(
                    'key' => 'field_64f5a987ab0c3',
                    'label' => 'Картинка',
                    'name' => 'image',
                    'aria-label' => '',
                    'type' => 'image',
                    'instructions' => '',
                    'required' => 1,
                    'conditional_logic' => 0,
                    'wrapper' => array(
                        'width' => '',
                        'class' => '',
                        'id' => '',
                    ),
                    'acfe_save_meta' => 0,
                    'uploader' => '',
                    'return_format' => 'id',
                    'acfe_thumbnail' => 0,
                    'min_width' => '',
                    'min_height' => '',
                    'min_size' => '',
                    'max_width' => '',
                    'max_height' => '',
                    'max_size' => '',
                    'mime_types' => '',
                    'preview_size' => 'medium',
                    'library' => 'all',
                    'parent_repeater' => 'field_64f5a91dab0c1',
                ),
                array(
                    'key' => 'field_64f5a987ab0c4',
                    'label' => 'Название',
                    'name' => 'name',
                    'aria-label' => '',
                    'type' => 'text',
                    'instructions' => '',
                    'required' => 1,
                    'conditional_logic' => 0,
                    'wrapper' => array(
                        'width' => '',
                        'class' => '',
                        'id' => '',
                    ),
                    'acfe_save_meta' => 0,
                    'default_value' => '',
                    'maxlength' => '',
                    'placeholder' => '',
                    'prepend' => '',
                    'append' => '',
                    'parent_repeater' => 'field_64f5a91dab0c1',
                ),
                array(
                    'key' => 'field_64f5a9aaab0c5',
                    'label' => 'Цена',
                    'name' => 'price',
                    'aria-label' => '',
                    'type' => 'number',
                    'instructions' => '',
                    'required' => 1,
                    'conditional_logic' => 0,
                    'wrapper' => array(
                        'width' => '',
                        'class' => '',
                        'id' => '',
                    ),
                    'acfe_save_meta' => 0,
                    'default_value' => '',
                    'min' => '',
                    'max' => '',
                    'placeholder' => '',
                    'step' => '',
                    'prepend' => '',
                    'append' => '',
                    'parent_repeater' => 'field_64f5a91dab0c1',
                ),
                array(
                    'key' => 'field_64f5a9b2ab0c6',
                    'label' => 'Доп. час',
                    'name' => 'second_price',
                    'aria-label' => '',
                    'type' => 'number',
                    'instructions' => '',
                    'required' => 0,
                    'conditional_logic' => 0,
                    'wrapper' => array(
                        'width' => '',
                        'class' => '',
                        'id' => '',
                    ),
                    'acfe_save_meta' => 0,
                    'default_value' => '',
                    'min' => '',
                    'max' => '',
                    'placeholder' => '',
                    'step' => '',
                    'prepend' => '',
                    'append' => '',
                    'parent_repeater' => 'field_64f5a91dab0c1',
                ),
            ),
        ),
        array(
            'key' => 'additional2',
            'label' => 'Дополнительно',
            'name' => 'additional2',
            'aria-label' => '',
            'type' => 'repeater',
            'instructions' => '',
            'required' => 0,
            'conditional_logic' => 0,
            'wrapper' => array(
                'width' => '',
                'class' => '',
                'id' => '',
            ),
            'acfe_save_meta' => 0,
            'acfe_repeater_stylised_button' => 0,
            'layout' => 'table',
            'pagination' => 0,
            'hide_collapse' => 0,
            'collapse_all_repeater' => 0,
            'btn-icon-only' => 0,
            'min' => 0,
            'max' => 0,
            'collapsed' => '',
            'button_label' => 'Добавить',
            'rows_per_page' => 20,
            'sub_fields' => array(
                array(
                    'key' => 'image',
                    'label' => 'Картинка',
                    'name' => 'image',
                    'aria-label' => '',
                    'type' => 'image',
                    'instructions' => '',
                    'required' => 1,
                    'conditional_logic' => 0,
                    'wrapper' => array(
                        'width' => '',
                        'class' => '',
                        'id' => '',
                    ),
                    'acfe_save_meta' => 0,
                    'uploader' => '',
                    'return_format' => 'id',
                    'acfe_thumbnail' => 0,
                    'min_width' => '',
                    'min_height' => '',
                    'min_size' => '',
                    'max_width' => '',
                    'max_height' => '',
                    'max_size' => '',
                    'mime_types' => '',
                    'preview_size' => 'medium',
                    'library' => 'all',
                    'parent_repeater' => 'additional2',
                ),
                array(
                    'key' => 'name',
                    'label' => 'Название',
                    'name' => 'name',
                    'aria-label' => '',
                    'type' => 'text',
                    'instructions' => '',
                    'required' => 1,
                    'conditional_logic' => 0,
                    'wrapper' => array(
                        'width' => '',
                        'class' => '',
                        'id' => '',
                    ),
                    'acfe_save_meta' => 0,
                    'default_value' => '',
                    'maxlength' => '',
                    'placeholder' => '',
                    'prepend' => '',
                    'append' => '',
                    'parent_repeater' => 'additional2',
                ),
                array(
                    'key' => 'price',
                    'label' => 'Цена',
                    'name' => 'price',
                    'aria-label' => '',
                    'type' => 'number',
                    'instructions' => '',
                    'required' => 1,
                    'conditional_logic' => 0,
                    'wrapper' => array(
                        'width' => '',
                        'class' => '',
                        'id' => '',
                    ),
                    'acfe_save_meta' => 0,
                    'default_value' => '',
                    'min' => '',
                    'max' => '',
                    'placeholder' => '',
                    'step' => '',
                    'prepend' => '',
                    'append' => '',
                    'parent_repeater' => 'additional2',
                ),
            ),
        ),
    )
    );

    acf_add_local_field_group(array(
        'key' => 'group_64f5a4b7d3e33',
        'title' => 'Мастрер-класс поля записи',
        'fields' => $fields,
        'location' => array(
            array(
                array(
                    'param' => 'post_type',
                    'operator' => '==',
                    'value' => 'masterclass',
                ),
            ),
        ),
        'menu_order' => 0,
        'position' => 'normal',
        'style' => 'default',
        'label_placement' => 'left',
        'instruction_placement' => 'label',
        'hide_on_screen' => '',
        'active' => true,
        'description' => '',
        'show_in_rest' => 0,
        'acfe_display_title' => '',
        'acfe_autosync' => '',
        'acfe_form' => 0,
        'acfe_meta' => '',
        'acfe_note' => '',
    ));

    acf_add_local_field_group(array(
        'key' => 'group_64f553cdd549d',
        'title' => 'Мастер-классы поля',
        'fields' => array(
            array(
                'key' => 'field_64f553ce0775f',
                'label' => 'Проведенные мастер-классы',
                'name' => 'archived_events',
                'aria-label' => '',
                'type' => 'relationship',
                'instructions' => '',
                'required' => 0,
                'conditional_logic' => 0,
                'wrapper' => array(
                    'width' => '',
                    'class' => '',
                    'id' => '',
                ),
                'acfe_save_meta' => 0,
                'post_type' => '',
                'taxonomy' => '',
                'filters' => array(
                    0 => 'search',
                    1 => 'post_type',
                    2 => 'taxonomy',
                ),
                'post_type' => array(
                    0 => 'archived_masterclass',
                ),
                'return_format' => 'object',
                'acfe_bidirectional' => array(
                    'acfe_bidirectional_enabled' => '0',
                ),
                'min' => '',
                'max' => '',
                'elements' => '',
            ),
            array(
                'key' => 'masterclass_archive_background',
                'label' => 'Банер',
                'name' => 'background',
                'aria-label' => '',
                'type' => 'image',
                'instructions' => '',
                'required' => 0,
                'conditional_logic' => 0,
                'wrapper' => array(
                    'width' => '',
                    'class' => '',
                    'id' => '',
                ),
                'acfe_save_meta' => 0,
                'uploader' => '',
                'return_format' => 'id',
                'acfe_thumbnail' => 0,
                'min_width' => '',
                'min_height' => '',
                'min_size' => '',
                'max_width' => '',
                'max_height' => '',
                'max_size' => '',
                'mime_types' => '',
                'preview_size' => 'medium',
                'library' => 'all',
            ),
            array(
                'key' => 'masterclass_archive_thumb',
                'label' => 'Изображение',
                'name' => 'thumb',
                'aria-label' => '',
                'type' => 'image',
                'instructions' => '',
                'required' => 0,
                'conditional_logic' => 0,
                'wrapper' => array(
                    'width' => '',
                    'class' => '',
                    'id' => '',
                ),
                'acfe_save_meta' => 0,
                'uploader' => '',
                'return_format' => 'id',
                'acfe_thumbnail' => 0,
                'min_width' => '',
                'min_height' => '',
                'min_size' => '',
                'max_width' => '',
                'max_height' => '',
                'max_size' => '',
                'mime_types' => '',
                'preview_size' => 'medium',
                'library' => 'all',
            ),
            array(
                'key' => 'sales',
                'label' => 'Выгодные предложения',
                'name' => 'sales',
                'aria-label' => '',
                'type' => 'gallery',
                'instructions' => '',
                'required' => 0,
                'conditional_logic' => 0,
                'wrapper' => array(
                    'width' => '',
                    'class' => '',
                    'id' => '',
                ),
                'acfe_save_meta' => 0,
                'return_format' => 'id',
                'library' => 'all',
                'min' => '',
                'max' => '',
                'min_width' => '',
                'min_height' => '',
                'min_size' => '',
                'max_width' => '',
                'max_height' => '',
                'max_size' => '',
                'mime_types' => '',
                'insert' => 'append',
                'preview_size' => 'medium',
            ),
            array(
                'key' => 'field_64f5542d07760',
                'label' => 'Отзывы',
                'name' => 'reviews',
                'aria-label' => '',
                'type' => 'gallery',
                'instructions' => '',
                'required' => 0,
                'conditional_logic' => 0,
                'wrapper' => array(
                    'width' => '',
                    'class' => '',
                    'id' => '',
                ),
                'acfe_save_meta' => 0,
                'return_format' => 'id',
                'library' => 'all',
                'min' => '',
                'max' => '',
                'min_width' => '',
                'min_height' => '',
                'min_size' => '',
                'max_width' => '',
                'max_height' => '',
                'max_size' => '',
                'mime_types' => '',
                'insert' => 'append',
                'preview_size' => 'medium',
            ),
            array(
                'key' => 'field_64f5544a07761',
                'label' => 'ЧАВО',
                'name' => 'faq',
                'aria-label' => '',
                'type' => 'repeater',
                'instructions' => '',
                'required' => 0,
                'conditional_logic' => 0,
                'wrapper' => array(
                    'width' => '',
                    'class' => '',
                    'id' => '',
                ),
                'acfe_save_meta' => 0,
                'acfe_repeater_stylised_button' => 0,
                'layout' => 'table',
                'pagination' => 0,
                'hide_collapse' => 0,
                'collapse_all_repeater' => 0,
                'btn-icon-only' => 0,
                'min' => 0,
                'max' => 0,
                'collapsed' => '',
                'button_label' => 'Добавить',
                'rows_per_page' => 20,
                'sub_fields' => array(
                    array(
                        'key' => 'field_64f5546007762',
                        'label' => 'Вопрос',
                        'name' => 'faq_title',
                        'aria-label' => '',
                        'type' => 'text',
                        'instructions' => '',
                        'required' => 0,
                        'conditional_logic' => 0,
                        'wrapper' => array(
                            'width' => '',
                            'class' => '',
                            'id' => '',
                        ),
                        'acfe_save_meta' => 0,
                        'default_value' => '',
                        'maxlength' => '',
                        'placeholder' => '',
                        'prepend' => '',
                        'append' => '',
                        'parent_repeater' => 'field_64f5544a07761',
                    ),
                    array(
                        'key' => 'field_64f5547b07763',
                        'label' => 'Ответ',
                        'name' => 'faq_answer',
                        'aria-label' => '',
                        'type' => 'textarea',
                        'instructions' => '',
                        'required' => 0,
                        'conditional_logic' => 0,
                        'wrapper' => array(
                            'width' => '',
                            'class' => '',
                            'id' => '',
                        ),
                        'acfe_save_meta' => 0,
                        'default_value' => '',
                        'acfe_textarea_code' => 0,
                        'maxlength' => '',
                        'rows' => '',
                        'placeholder' => '',
                        'new_lines' => '',
                        'parent_repeater' => 'field_64f5544a07761',
                    ),
                ),
            ),
            array(
                'key' => 'seo',
                'label' => 'SEO',
                'name' => 'seo',
                'aria-label' => '',
                'type' => 'repeater',
                'instructions' => '',
                'required' => 0,
                'conditional_logic' => 0,
                'wrapper' => array(
                    'width' => '',
                    'class' => '',
                    'id' => '',
                ),
                'acfe_save_meta' => 0,
                'acfe_repeater_stylised_button' => 0,
                'layout' => 'block',
                'pagination' => 0,
                'hide_collapse' => 0,
                'collapse_all_repeater' => 0,
                'btn-icon-only' => 0,
                'min' => 0,
                'max' => 0,
                'collapsed' => '',
                'button_label' => 'Добавить',
                'rows_per_page' => 20,
                'sub_fields' => array(
                    array(
                        'key' => 'seo_title',
                        'label' => 'Заголовок',
                        'name' => 'seo_title',
                        'aria-label' => '',
                        'type' => 'text',
                        'instructions' => '',
                        'required' => 0,
                        'conditional_logic' => 0,
                        'wrapper' => array(
                            'width' => '',
                            'class' => '',
                            'id' => '',
                        ),
                        'acfe_save_meta' => 0,
                        'default_value' => '',
                        'maxlength' => '',
                        'placeholder' => '',
                        'prepend' => '',
                        'append' => '',
                        'parent_repeater' => 'seo',
                    ),
                    array(
                        'key' => 'seo_text',
                        'label' => 'Текст',
                        'name' => 'seo_text',
                        'aria-label' => '',
                        'type' => 'textarea',
                        'instructions' => '',
                        'required' => 0,
                        'conditional_logic' => 0,
                        'wrapper' => array(
                            'width' => '',
                            'class' => '',
                            'id' => '',
                        ),
                        'acfe_save_meta' => 0,
                        'default_value' => '',
                        'acfe_textarea_code' => 0,
                        'maxlength' => '',
                        'rows' => '',
                        'placeholder' => '',
                        'new_lines' => '',
                        'parent_repeater' => 'seo',
                    ),
                ),
            ),
        ),
        'location' => array(
            array(
                array(
                    'param' => 'options_page',
                    'operator' => '==',
                    'value' => 'masterclass-archive',
                ),
            ),
        ),
        'menu_order' => 0,
        'position' => 'normal',
        'style' => 'default',
        'label_placement' => 'left',
        'instruction_placement' => 'label',
        'hide_on_screen' => '',
        'active' => true,
        'description' => '',
        'show_in_rest' => 0,
        'acfe_display_title' => '',
        'acfe_autosync' => '',
        'acfe_form' => 0,
        'acfe_meta' => '',
        'acfe_note' => '',
    ));
    
    acf_add_local_field_group(array(
        'key' => 'group_6500d77aab69d',
        'title' => 'Мастер-классы категории поля',
        'fields' => array(
            array(
                'key' => 'field_6500d77bb6627',
                'label' => 'Банер',
                'name' => 'background',
                'aria-label' => '',
                'type' => 'image',
                'instructions' => '',
                'required' => 0,
                'conditional_logic' => 0,
                'wrapper' => array(
                    'width' => '',
                    'class' => '',
                    'id' => '',
                ),
                'acfe_save_meta' => 0,
                'uploader' => '',
                'return_format' => 'id',
                'acfe_thumbnail' => 0,
                'min_width' => '',
                'min_height' => '',
                'min_size' => '',
                'max_width' => '',
                'max_height' => '',
                'max_size' => '',
                'mime_types' => '',
                'preview_size' => 'medium',
                'library' => 'all',
            ),

            array(
                'key' => 'masterclass-cat-tags',
                'label' => 'Метки',
                'name' => 'метки',
                'aria-label' => '',
                'type' => 'repeater',
                'instructions' => '',
                'required' => 0,
                'conditional_logic' => 0,
                'wrapper' => array(
                    'width' => '100',
                    'class' => '',
                    'id' => '',
                ),
                'acfe_save_meta' => 0,
                'acfe_repeater_stylised_button' => 0,
                'layout' => 'table',
                'pagination' => 0,
                'hide_collapse' => 0,
                'collapse_all_repeater' => 0,
                'btn-icon-only' => 0,
                'acfe_settings' => '',
                'min' => 0,
                'max' => 30,
                'acfe_permissions' => '',
                'collapsed' => '',
                'button_label' => 'Добавить',
                'rows_per_page' => 20,
                'sub_fields' => array(
                    array(
                        'key' => 'masterclass-cat-tags-text',
                        'label' => 'Текст',
                        'name' => 'текст',
                        'aria-label' => '',
                        'type' => 'text',
                        'instructions' => '',
                        'required' => 0,
                        'conditional_logic' => 0,
                        'wrapper' => array(
                            'width' => '',
                            'class' => '',
                            'id' => '',
                        ),
                        'default_value' => '',
                        'placeholder' => '',
                        'prepend' => '',
                        'append' => '',
                        'maxlength' => '',
                        'parent_repeater' => 'masterclass-cat-tags',
                    ),
                    array(
                        'key' => 'masterclass-cat-tags-name',
                        'label' => 'Название метки',
                        'name' => 'название_метки',
                        'aria-label' => '',
                        'type' => 'text',
                        'instructions' => 'Название метки указанное в товарах',
                        'required' => 0,
                        'conditional_logic' => 0,
                        'wrapper' => array(
                            'width' => '',
                            'class' => '',
                            'id' => '',
                        ),
                        'default_value' => '',
                        'placeholder' => '',
                        'prepend' => '',
                        'append' => '',
                        'maxlength' => '',
                        'parent_repeater' => 'masterclass-cat-tags',
                    ),
                    array(
                        'key' => 'masterclass-cat-tags-icon',
                        'label' => 'Иконка',
                        'name' => 'иконка',
                        'aria-label' => '',
                        'type' => 'image',
                        'instructions' => '',
                        'required' => 0,
                        'conditional_logic' => 0,
                        'wrapper' => array(
                            'width' => '',
                            'class' => '',
                            'id' => '',
                        ),
                        'return_format' => 'url',
                        'preview_size' => 'full',
                        'library' => 'all',
                        'min_width' => 60,
                        'min_height' => '',
                        'min_size' => '',
                        'max_width' => '',
                        'max_height' => '',
                        'max_size' => '',
                        'mime_types' => '',
                        'uploader' => '',
                        'acfe_thumbnail' => 0,
                        'parent_repeater' => 'masterclass-cat-tags',
                    ),
                    array(
                        'key' => 'masterclass-cat-tags-cat',
                        'label' => 'Категория',
                        'name' => 'рубрика',
                        'aria-label' => '',
                        'type' => 'taxonomy',
                        'instructions' => '',
                        'required' => 0,
                        'conditional_logic' => 0,
                        'wrapper' => array(
                            'width' => '',
                            'class' => '',
                            'id' => '',
                        ),
                        'acfe_save_meta' => 0,
                        'taxonomy' => 'masterclass-cat',
                        'add_term' => 1,
                        'save_terms' => 0,
                        'load_terms' => 0,
                        'return_format' => 'id',
                        'field_type' => 'multi_select',
                        'allow_null' => 0,
                        'acfe_bidirectional' => array(
                            'acfe_bidirectional_enabled' => '0',
                        ),
                        'acfe_settings' => '',
                        'acfe_validate' => '',
                        'acfe_permissions' => '',
                        'multiple' => 0,
                        'parent_repeater' => 'masterclass-cat-tags',
                    ),
                ),
            ),
        ),
        'location' => array(
            array(
                array(
                    'param' => 'taxonomy',
                    'operator' => '==',
                    'value' => 'masterclass-cat',
                ),
            ),
        ),
        'menu_order' => 0,
        'position' => 'normal',
        'style' => 'default',
        'label_placement' => 'left',
        'instruction_placement' => 'label',
        'hide_on_screen' => '',
        'active' => true,
        'description' => '',
        'show_in_rest' => 0,
        'acfe_display_title' => '',
        'acfe_autosync' => '',
        'acfe_form' => 0,
        'acfe_meta' => '',
        'acfe_note' => '',
    ));

    acf_add_local_field_group(array(
        'key' => 'group_6500e1bf326ce',
        'title' => 'tt3',
        'fields' => array(
            array(
                'key' => 'field_6500e1bf4b4d4',
                'label' => 'Галлерея',
                'name' => 'gallery',
                'aria-label' => '',
                'type' => 'repeater',
                'instructions' => '',
                'required' => 0,
                'conditional_logic' => 0,
                'wrapper' => array(
                    'width' => '',
                    'class' => '',
                    'id' => '',
                ),
                'acfe_save_meta' => 0,
                'acfe_repeater_stylised_button' => 0,
                'layout' => 'table',
                'pagination' => 0,
                'hide_collapse' => 0,
                'collapse_all_repeater' => 0,
                'btn-icon-only' => 0,
                'min' => 0,
                'max' => 0,
                'collapsed' => '',
                'button_label' => 'Добавить',
                'rows_per_page' => 20,
                'sub_fields' => array(
                    array(
                        'key' => 'field_6500e1dc4b4d5',
                        'label' => 'Youtube',
                        'name' => 'youtube',
                        'aria-label' => '',
                        'type' => 'link',
                        'instructions' => '',
                        'required' => 0,
                        'conditional_logic' => 0,
                        'wrapper' => array(
                            'width' => '',
                            'class' => '',
                            'id' => '',
                        ),
                        'acfe_save_meta' => 0,
                        'return_format' => 'url',
                        'parent_repeater' => 'field_6500e1bf4b4d4',
                    ),
                    array(
                        'key' => 'field_6500e1ff4b4d6',
                        'label' => 'Фото',
                        'name' => 'photo',
                        'aria-label' => '',
                        'type' => 'image',
                        'instructions' => '',
                        'required' => 0,
                        'conditional_logic' => 0,
                        'wrapper' => array(
                            'width' => '',
                            'class' => '',
                            'id' => '',
                        ),
                        'acfe_save_meta' => 0,
                        'uploader' => '',
                        'return_format' => 'id',
                        'acfe_thumbnail' => 0,
                        'min_width' => '',
                        'min_height' => '',
                        'min_size' => '',
                        'max_width' => '',
                        'max_height' => '',
                        'max_size' => '',
                        'mime_types' => '',
                        'preview_size' => 'medium',
                        'library' => 'all',
                        'parent_repeater' => 'field_6500e1bf4b4d4',
                    ),
                ),
            ),
        ),
        'location' => array(
            array(
                array(
                    'param' => 'post_type',
                    'operator' => '==',
                    'value' => 'masterclass',
                ),
            ),
        ),
        'menu_order' => 0,
        'position' => 'normal',
        'style' => 'default',
        'label_placement' => 'left',
        'instruction_placement' => 'label',
        'hide_on_screen' => '',
        'active' => true,
        'description' => '',
        'show_in_rest' => 0,
        'acfe_display_title' => '',
        'acfe_autosync' => '',
        'acfe_form' => 0,
        'acfe_meta' => '',
        'acfe_note' => '',
    ));


    acf_add_options_page(array(
        'menu_slug' => 'masterclass-archive',
        'page_title' => 'Мастерклассы',
        'active' => true,
        'menu_title' => 'Настройки',
        'capability' => 'manage_options',
        'parent_slug' => 'edit.php?post_type=masterclass',
        'position' => '',
        'icon_url' => '',
        'redirect' => true,
        'post_id' => 'masterclass',
        'autoload' => false,
        'update_button' => 'Обновить',
        'updated_message' => 'Настройки были обновлены',
    ));
}
